### ISSUE TITLE
Formatting issues on some daily dates

### ISSUE THREAD

**Issue by bspain** [bspain/crlife-series#26]
Looks like some encoded content is causing issues

![image](https://user-images.githubusercontent.com/2678462/71431025-d5128f00-2694-11ea-87fc-eb7033edbff2.png)

e.g. http://crlife-series.azurewebsites.net/daily?ref=1226

Impacted dates:
0130
0213
0218
0515
0516
0523
0627
0815
0820
1029
1113
1114
1121
1226

**Comment by bspain** [comment]
cc: @idjohnson

**Comment by bspain** [comment]
This is a problem in the source for the verse directly.  API.NLT.TO is embedding the "span" within the "p" for the chapter-number.

![image](https://user-images.githubusercontent.com/2678462/71447490-7c72de80-26f4-11ea-8773-a7f35656ada1.png)

Moving the "span" outside the "p" will cause it to get styled correctly as a footnote

![image](https://user-images.githubusercontent.com/2678462/71447497-957b8f80-26f4-11ea-8cce-a6e43a708c95.png)

The simplest fix for now, is to just hand-edit the 14 impacted dates.  This could be a problem if/when down the road we are fetching bible verses from api.nlt.to in a more dynamic/real-time fashion.

**Comment by idjohnson** [comment]
Interesting.  Good to know. Did you edit the 14?

**Comment by bspain** [comment]
I'm working on this now - I'm just using the CLI tools to make the necessary edits by hand.

**Comment by bspain** [comment]
Fixed all impacted dates
